select * from Clientes

insert into Reservas (descripcion)
values ('Reservado')
insert into Reservas (descripcion)
values ('NO Reservado')

INSERT INTO tipo_peliculas (genero) VALUES ('Acción')
INSERT INTO tipo_peliculas (genero) VALUES ('Aventuras')
INSERT INTO tipo_peliculas (genero) VALUES ('Ciencia Ficción')
INSERT INTO tipo_peliculas (genero) VALUES ('Comedia')
INSERT INTO tipo_peliculas (genero) VALUES ('Animacion')
INSERT INTO tipo_peliculas (genero) VALUES ('Drama')
INSERT INTO tipo_peliculas (genero) VALUES ('Fantasía')
INSERT INTO tipo_peliculas (genero) VALUES ('Musical')
INSERT INTO tipo_peliculas (genero) VALUES ('Suspense')
INSERT INTO tipo_peliculas (genero) VALUES ('Terror')

INSERT INTO PELICULAS (Titulo, duracion, descripcion, id_tipo) VALUES ('Toy Story 3', 103 , 'Woody (Tom Hanks), Buzz (Tim Allen) y el resto de los juguetes terminan en una guardería luego de que Andy se va al colegio.', 5)

INSERT INTO PELICULAS (Titulo, duracion, descripcion, id_tipo) VALUES ('Cisne Negro', 107 , 'Una bailarina empieza a perder el frágil sentido de la realidad cuando una compañera recién llegada amenaza con usurpar su posición en el papel principal de "El lago de los cisnes".', 6)

INSERT INTO PELICULAS (Titulo, duracion, descripcion, id_tipo) VALUES ('Scott Pilgrim contra el mundo', 112, 'Después de conocer a la mujer de sus sueños, Scott Pilgrim debe enfrentarse a un ejército de exparejas que quieren deshacerse de él.',4)

INSERT INTO PELICULAS (Titulo, duracion, descripcion, id_tipo) VALUES ('Drive', 100 , 'Un doble de cine de Hollywood que trabaja como conductor para criminales empieza a recibir amenazas de muerte después de un robo fallido', 1)

INSERT INTO PELICULAS (Titulo, duracion, descripcion, id_tipo) VALUES ('Los Vengadores', 143 , 'El director de la Agencia SHIELD decide reclutar a un equipo para salvar al mundo de un desastre casi seguro cuando un enemigo inesperado surge como una gran amenaza para la seguridad mundial.',3)

INSERT INTO PELICULAS (Titulo, duracion, descripcion, id_tipo) VALUES ('The Lords of Salem', 101 , 'La DJ de una radio en Salem comienza a ser hostigada por visiones y pesadillas de unas brujas vengativas después de programar una canción de un misterioso grupo del que sólo se conoce su nombre, "The Lords". ', 9)

INSERT INTO PELICULAS (Titulo, duracion, descripcion, id_tipo) VALUES ('Los ilusos', 93 , 'Película sobre el deseo de hacer cine, o sobre lo que hacen algunos cineastas cuando no hacen cine; sobre perder el tiempo y el tiempo perdido; sobre conversaciones, borracheras, comidas y rutinas; sobre los paseos al salir del cine.
', 5)

INSERT INTO PELICULAS (Titulo, duracion, descripcion, id_tipo) VALUES ('Interstellar ', 169 , 'Gracias a un descubrimiento, un grupo de científicos y exploradores, encabezados por Cooper, se embarcan en un viaje espacial para encontrar un lugar con las condiciones necesarias para reemplazar a la Tierra y comenzar una nueva vida allí.', 2)

INSERT INTO PELICULAS (Titulo, duracion, descripcion, id_tipo) VALUES ('El Gran Hotel Budapest',100 , 'El conserje de un elegante hotel europeo inicia una interesante amistad con un joven compañero de trabajo.', 4)

INSERT INTO PELICULAS (Titulo, duracion, descripcion, id_tipo) VALUES ('Relatos salvajes', 122 , 'Seis relatos que alternan la intriga, la comedia y la violencia. Sus personajes se verán empujados hacia el abismo y hacia el innegable placer de perder el control al cruzar la delgada línea que separa la civilización de la barbarie.',6)

INSERT INTO PELICULAS (Titulo, duracion, descripcion, id_tipo) VALUES ('La bruja', 92 , 'Nueva Inglaterra, 1630. Una familia compuesta por un matrimonio de colonos cristianos, padres de cinco hijos, vive cerca de un bosque al que la leyenda popular atribuye un carácter demoníaco. La convivencia estalla y la familia se desgarra al sospechar que su hija mayor practica la brujería, debido a que las cosechas no crecen y su bebé ha desaparecido.', 10)

INSERT INTO PELICULAS (Titulo, duracion, descripcion, id_tipo) VALUES ('La ciudad de las estrellas', 128 , 'Sebastian, un pianista de jazz, y Mia, una aspirante a actriz, se enamoran locamente; pero la ambición desmedida que tienen por triunfar en sus respectivas carreras, en una ciudad como Los Ángeles, repleta de competencia y carente de piedad, pone en peligro su amor.', 8)

insert into Funciones (id_pelicula,fecha_hora,idioma,pre_unitario)
values (2,'11/12/2022','Español Doblado',250.49)
insert into Funciones (id_pelicula,fecha_hora,idioma,pre_unitario)
values (1,'10/10/2022 20:00:00','Inglés Subtitulado',250.49)
insert into Funciones (id_pelicula,fecha_hora,idioma,pre_unitario)
values (3,'06/11/2022 21:30:00','Inglés Subtitulado',250.49)
insert into Funciones (id_pelicula,fecha_hora,idioma,pre_unitario)
values (5,'25/10/2022','Español Subtitulado',299.99)
insert into Funciones (id_pelicula,fecha_hora,idioma,pre_unitario)
values (4,'10/12/2022 18:00:00','Inglés Subtitulado',269.99)
insert into Funciones (id_pelicula,fecha_hora,idioma,pre_unitario)
values (7,'04/11/2022 19:30:00','Español Doblado',300)
insert into Funciones (id_pelicula,fecha_hora,idioma,pre_unitario)
values (6,'15/12/2022 21:30:00','Inglés Subtitulado',400)
insert into Funciones (id_pelicula,fecha_hora,idioma,pre_unitario)
values (12,'21/10/2022 20:00:00','Español Subtitulado',400)
insert into Funciones (id_pelicula,fecha_hora,idioma,pre_unitario)
values (8,'09/12/2022 22:30:00','Inglés Subtitulado',400)
insert into Funciones (id_pelicula,fecha_hora,idioma,pre_unitario)
values (11,'26/11/2022 21:30:00','Inglés Subtitulado',350)
insert into Funciones (id_pelicula,fecha_hora,idioma,pre_unitario)
values (9,'14/10/2022 19:30:00','Español Doblado',350)
insert into Funciones (id_pelicula,fecha_hora,idioma,pre_unitario)
values (10,'06/11/2022 21:30:00','Español Original',350)

INSERT INTO tipos_pagos  (nombre_tipo_pago) VALUES ('tarjeta de credito')
INSERT INTO tipos_pagos  (nombre_tipo_pago) VALUES ('pago en efectivo ')
INSERT INTO tipos_pagos  (nombre_tipo_pago ) VALUES ('tarjeta de debito')
INSERT INTO tipos_pagos  (nombre_tipo_pago ) VALUES ('transferencia')

INSERT INTO barrios (nombre_barrio) VALUES ('Villa Cabrera')
INSERT INTO barrios (nombre_barrio) VALUES ('Alto Verde')
INSERT INTO barrios (nombre_barrio) VALUES ('General Paz')
INSERT INTO barrios (nombre_barrio) VALUES ('Centro')
INSERT INTO barrios (nombre_barrio) VALUES ('Matienzo')

INSERT INTO Sucursales (id_barrio, nombre_sucursal, direccion) VALUES (1, 'Sucursal Villa Cabrera ', 'Los Sauces 1990')
INSERT INTO Sucursales (id_barrio, nombre_sucursal, direccion) VALUES (2, 'Sucursal Alto Verde ', 'Azor Grimaut 3268')
INSERT INTO Sucursales (id_barrio, nombre_sucursal, direccion) VALUES (3, 'Sucursal General Paz ', 'Hugo Miatello 230')
INSERT INTO Sucursales (id_barrio, nombre_sucursal, direccion) VALUES (4, 'Sucursal Centro ', 'Las Vertienes 6210')
INSERT INTO Sucursales (id_barrio, nombre_sucursal, direccion) VALUES (5, 'Sucursal Matienzo ', 'Av Colon 921')

INSERT INTO Tipo_salas (id_tipo_sala,tipo) VALUES (1,'2D')
INSERT INTO Tipo_salas (id_tipo_sala,tipo) VALUES (2,'3D')
INSERT INTO Tipo_salas (id_tipo_sala,tipo) VALUES (3,'3D envolvente')
INSERT INTO Tipo_salas (id_tipo_sala,tipo) VALUES (4,'4D')

INSERT INTO Salas (nombre_sala, id_tipo_sala) VALUES ('Sala 2d 1', 1)
INSERT INTO Salas (nombre_sala, id_tipo_sala) VALUES ('Sala 2d 2', 1)
INSERT INTO Salas (nombre_sala, id_tipo_sala) VALUES ('Sala 2d 3', 1)
INSERT INTO Salas (nombre_sala, id_tipo_sala) VALUES ('Sala 3d 1', 2)
INSERT INTO Salas (nombre_sala, id_tipo_sala) VALUES ('Sala 3d 2', 2)
INSERT INTO Salas (nombre_sala, id_tipo_sala) VALUES ('Sala 3d 3', 2)
INSERT INTO Salas (nombre_sala, id_tipo_sala) VALUES ('Sala 3D+ 1', 3)
INSERT INTO Salas (nombre_sala, id_tipo_sala) VALUES ('Sala 4D 1', 4)
INSERT INTO Salas (nombre_sala, id_tipo_sala) VALUES ('Sala 4D 2', 4)

INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Hugo Gonzalez','58151852','gonzalezhugo@gmail.com','3553522962919620')
INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Alejandro Rodriguez','25452452','ale2001@gmail.com','3578268019578020')
INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Gabriela Gomez','54642452','gabig0@gmail.com','5002352832203880')
INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Lucas Fernandez','43545342','lukitasf@gmail.com','3536518167376410')
INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Sofia Lopez','24524845','sofilope5@gmail.com','6397994849264720')
INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Raul Díaz','42424845','raul1967@gmail.com','3534943035988060')
INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Catalina Martínez','67434766','catmartinez2000@gmail.com','4175005070101880')
INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Jorge Perez','64131467','jorgep@gmail.com','5558530331440800')
INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Oscar García','55658498','garciaoscar@gmail.com','4936540162170008')
INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Clarisa Sanchez','56158142','clarisan@gmail.com','3746224205536376')
INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Mariana Romero','87945585','romeromari1913@gmail.com','2016720902660011')
INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Mariano Sosa','35782152','marianosos@gmail.com','3586157215602940')
INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Tomas Torres','81097851','tttomitt@gmail.com','6764104527630000')
INSERT INTO Clientes (nombre_cliente, dni_cliente, email, tarjeta_credito) VALUES ('Leonel Messi','74584185','messilionel10@gmail.com','5100144164988520')
INSERT INTO Clientes (nombre_cliente, dni_cliente,tarjeta_credito) VALUES ('Fulanito Fulanez','45244598','5783589527638877')
INSERT INTO Clientes (nombre_cliente, dni_cliente,tarjeta_credito) VALUES ('Mengano Menganez','11456395','7589124635894165')

INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 1)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 2)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 3)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 4)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 5)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 6)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 7)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 8)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 9)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 10)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 11)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 12)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 13)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 14)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 15)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 16)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 17)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 18)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 19)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (1 , 20)

INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 1)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 2)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 3)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 4)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 5)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 6)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 7)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 8)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 9)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 10)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 11)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 12)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 13)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 14)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 15)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 16)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 17)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 18)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 19)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (2 , 20)

INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 1)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 2)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 3)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 4)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 5)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 6)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 7)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 8)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 9)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 10)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 11)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 12)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 13)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 14)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 15)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 16)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 17)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 18)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 19)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (3 , 20)

INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 1)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 2)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 3)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 4)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 5)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 6)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 7)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 8)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 9)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 10)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 11)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 12)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 13)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 14)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 15)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 16)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 17)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 18)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 19)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (4 , 20)

INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 1)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 2)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 3)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 4)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 5)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 6)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 7)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 8)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 9)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 10)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 11)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 12)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 13)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 14)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5, 15)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 16)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 17)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 18)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 19)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (5 , 20)

INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 1)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 2)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 3)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 4)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 5)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 6)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 7)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 8)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 9)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 10)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 11)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 12)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 13)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 14)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 15)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 16)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 17)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 18)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 19)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (6 , 20)

INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 1)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 2)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 3)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 4)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 5)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 6)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 7)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 8)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 9)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 10)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 11)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 12)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 13)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 14)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 15)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 16)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 17)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 18)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 19)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (7 , 20)

INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 1)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 2)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 3)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 4)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 5)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 6)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 7)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 8)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 9)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 10)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 11)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 12)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 13)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 14)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 15)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 16)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 17)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 18)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 19)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (8 , 20)

INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 1)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 2)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 3)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 4)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 5)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 6)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 7)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 8)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 9)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 10)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 11)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 12)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 13)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 14)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 15)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 16)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 17)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 18)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 19)
INSERT INTO Asientos (id_sala, num_asiento) VALUES (9 , 20)